vich_uploader:
    db_driver: orm

    mappings:
        carousel_images:
            uri_prefix: '%carousel_images%'
            upload_destination: '%kernel.project_dir%/public%carousel_images%'
            namer: 
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above
            inject_on_load: true
        
        user_images:
            uri_prefix: '%user_images%'
            upload_destination: '%kernel.project_dir%/public%user_images%'
            namer: 
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above
            inject_on_load: true
    metadata:
        type: attribute
    