vich_uploader:
    db_driver: orm

    mappings:
        carousel_images:
            uri_prefix: '%carousel_images%'
            upload_destination: '%kernel.project_dir%/public%carousel_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    metadata:
        type: attribute
    